import {
  applyRetroactiveLearning,
  createEpistemicCore,
  createMemoryAttentionField,
  createPlasticMemoryGraph,
  createRejectedViewLedger,
  generateAndTriageAttentionViews,
  runAttentionDrivenMemoryCycle,
  type AttentionCandidate,
  type AttentionViewProposal,
  type ContextField,
  type VisionBranchCandidate,
} from "../src/index.js";

const now = "2026-07-30T18:00:00.000Z";
const contextField: ContextField = {
  revision: 1,
  updatedAt: now,
  transitions: [],
  frames: [
    {
      id: "context-atlas-memory",
      topic: "Prevent premature context loss",
      intent: "improve_memory_routing",
      summary: "Use several perspectives before reusing an old fix.",
      scope: { projectId: "project-atlas" },
      activation: 1,
      relevance: 1,
      inertia: 0.85,
      activationState: "dominant",
      retentionState: "pinned",
      introducedAt: now,
      lastReactivatedAt: now,
      parentFrameIds: [],
      sourceTurnIds: ["turn-1"],
      protectedReasons: ["Preserve the initial need until validation."],
    },
  ],
};

const epistemicCore = createEpistemicCore(
  [
    {
      id: "truth-bounded-retrieval",
      statement: "Memory retrieval must remain bounded and project-scoped.",
      state: "authoritative",
      scope: { projectId: "project-atlas" },
      sourceIds: ["source-atlas-spec"],
      confidence: 0.98,
      validFrom: now,
    },
  ],
  [
    {
      id: "source-atlas-spec",
      type: "documentation",
      trust: 0.97,
      independenceKey: "atlas-spec-v1",
      observedAt: now,
    },
  ],
  now,
);

const attentions: AttentionCandidate[] = [
  {
    id: "attention-goal",
    targetType: "goal",
    targetId: "preserve-initial-need",
    role: "goal",
    reason: "Keep the actual outcome visible throughout exploration.",
    scope: { projectId: "project-atlas" },
    contextAnchorIds: ["context-atlas-memory"],
    truthAnchorIds: [],
    goalDependency: 1,
    constraintImportance: 0.8,
    uncertainty: 0.2,
    novelty: 0.3,
    risk: 0.7,
    expectedInformationGain: 0.6,
    predictiveValue: 0.8,
    persistence: 1,
    urgency: 0.8,
    pinned: true,
  },
  {
    id: "attention-constraint",
    targetType: "truth_anchor",
    targetId: "truth-bounded-retrieval",
    role: "constraint",
    reason: "Prevent a broad global replay from entering the active View set.",
    scope: { projectId: "project-atlas" },
    contextAnchorIds: ["context-atlas-memory"],
    truthAnchorIds: ["truth-bounded-retrieval"],
    goalDependency: 0.8,
    constraintImportance: 1,
    uncertainty: 0.1,
    novelty: 0.2,
    risk: 0.9,
    expectedInformationGain: 0.5,
    predictiveValue: 0.9,
    persistence: 0.9,
    urgency: 0.8,
  },
  {
    id: "attention-unknown",
    targetType: "unknown",
    targetId: "actual-failure-mechanism",
    role: "uncertainty",
    reason: "The previous symptom may have a different cause in this context.",
    scope: { projectId: "project-atlas" },
    contextAnchorIds: ["context-atlas-memory"],
    truthAnchorIds: [],
    goalDependency: 0.7,
    constraintImportance: 0.6,
    uncertainty: 1,
    novelty: 0.8,
    risk: 0.75,
    expectedInformationGain: 0.95,
    predictiveValue: 0.65,
    persistence: 0.6,
    urgency: 0.85,
  },
  {
    id: "attention-pattern",
    targetType: "pattern",
    targetId: "pattern-premature-context-drop",
    role: "experience",
    reason: "Check whether an earlier context-loss pattern truly applies.",
    scope: { projectId: "project-atlas" },
    contextAnchorIds: ["context-atlas-memory"],
    truthAnchorIds: [],
    goalDependency: 0.65,
    constraintImportance: 0.55,
    uncertainty: 0.55,
    novelty: 0.45,
    risk: 0.6,
    expectedInformationGain: 0.75,
    predictiveValue: 0.8,
    persistence: 0.7,
    urgency: 0.65,
  },
  {
    id: "attention-challenge",
    targetType: "contradiction",
    targetId: "challenge-historical-reuse",
    role: "challenge",
    reason: "Search for evidence that the historical pattern is not applicable.",
    scope: { projectId: "project-atlas" },
    contextAnchorIds: ["context-atlas-memory"],
    truthAnchorIds: [],
    goalDependency: 0.55,
    constraintImportance: 0.7,
    uncertainty: 0.85,
    novelty: 0.75,
    risk: 0.8,
    expectedInformationGain: 0.9,
    predictiveValue: 0.6,
    persistence: 0.45,
    urgency: 0.7,
  },
];

const branches: VisionBranchCandidate[] = [
  {
    id: "branch-context-release",
    path: "/project-atlas/context/release",
    scope: { projectId: "project-atlas" },
    requiredConstraints: ["preserve_initial_need"],
    predictedEffects: ["restore_context_contract"],
    patternIds: ["pattern-premature-context-drop"],
    priorUtility: 0.86,
    evidenceConfidence: 0.8,
  },
  {
    id: "branch-transition-loss",
    path: "/project-atlas/context/transition",
    scope: { projectId: "project-atlas" },
    requiredConstraints: ["preserve_initial_need"],
    predictedEffects: ["reconstruct_transition"],
    patternIds: ["pattern-transition-loss"],
    priorUtility: 0.8,
    evidenceConfidence: 0.76,
  },
  {
    id: "branch-global-replay",
    path: "/project-atlas/global-replay",
    scope: { projectId: "project-atlas" },
    requiredConstraints: [],
    predictedEffects: ["global_memory_replay"],
    patternIds: [],
    priorUtility: 0.98,
    evidenceConfidence: 0.95,
  },
];

const proposals: AttentionViewProposal[] = [
  {
    id: "view-context-release",
    hypothesis: "The initial context was released before its constraints were transferred.",
    attentionIds: ["attention-goal", "attention-constraint", "attention-pattern"],
    truthAnchorIds: ["truth-bounded-retrieval"],
    assumptionIds: ["assumption-same-mechanism"],
    branchIds: ["branch-context-release"],
    questionsCovered: ["Was the initial context released too early?"],
    conclusions: [
      {
        key: "preserve",
        statement: "Keep the initial need pinned until validation.",
        confidence: 0.9,
      },
    ],
    scope: { projectId: "project-atlas" },
    sharedAcrossProjects: false,
    priorUtility: 0.88,
    noveltyScore: 0.55,
    expectedCost: 0.2,
    riskIfWrong: 0.45,
  },
  {
    id: "view-transition-loss",
    hypothesis: "The context exists, but the transition explaining its role was lost.",
    attentionIds: ["attention-goal", "attention-unknown", "attention-challenge"],
    truthAnchorIds: ["truth-bounded-retrieval"],
    assumptionIds: [],
    branchIds: ["branch-transition-loss"],
    questionsCovered: ["Was the transition path lost?"],
    conclusions: [
      {
        key: "preserve",
        statement: "Keep the initial need pinned until validation.",
        confidence: 0.86,
      },
    ],
    scope: { projectId: "project-atlas" },
    sharedAcrossProjects: false,
    priorUtility: 0.8,
    noveltyScore: 0.75,
    expectedCost: 0.25,
    riskIfWrong: 0.4,
  },
  {
    id: "view-global-replay",
    hypothesis: "Replay the complete memory to avoid missing context.",
    attentionIds: ["attention-goal"],
    truthAnchorIds: [],
    assumptionIds: [],
    branchIds: ["branch-global-replay"],
    questionsCovered: ["Can global replay recover the context?"],
    conclusions: [],
    scope: { projectId: "project-atlas" },
    sharedAcrossProjects: false,
    priorUtility: 0.95,
    noveltyScore: 0.1,
    expectedCost: 1,
    riskIfWrong: 0.95,
  },
];

const task = {
  intent: "improve_memory_routing",
  target: "attention-driven retrieval",
  projectId: "project-atlas",
  expectedOutcome: "Recover only the context needed to prevent the repeated failure.",
  operations: ["allocate_attention", "generate_views", "triage", "retrieve"],
  constraints: ["preserve_initial_need", "bounded_retrieval"],
  forbiddenEffects: ["global_memory_replay"],
};

const cycle = runAttentionDrivenMemoryCycle({
  task,
  scope: { projectId: "project-atlas" },
  contextField,
  epistemicCore,
  memoryRevision: 5,
  attentionCandidates: attentions,
  viewProposals: proposals,
  branches,
  equilibriumObservation: {
    visitedMemoryItems: 14,
    injectedMemoryItems: 2,
    averageExplorationDepth: 3,
    dominantViewHistory: [],
    changedContextIds: ["context-atlas-memory"],
    changedTruthAnchorIds: [],
    explorationDebt: [
      {
        id: "debt-mechanism",
        question: "Which context failure mechanism is active?",
        criticality: 0.8,
        coverage: 0.6,
        riskIfIgnored: 0.75,
        assignedViewIds: ["view-context-release", "view-transition-loss"],
      },
    ],
  },
  now,
});

console.log("Active attention:", cycle.attentionField.activeFocusIds);
console.log("Dominant View:", cycle.triage.dominantViewId);
console.log("Rejected Views:", cycle.triage.rejectedTraces.map((trace) => trace.viewId));
console.log("Consensus:", cycle.triage.consensus.consensus);
console.log("Equilibrium decisions:", cycle.equilibrium.decisions);

const selectedView = cycle.triage.dominantViewId ?? cycle.triage.activeViewIds[0]!;
const retroaction = applyRetroactiveLearning({
  attentionField: cycle.attentionField,
  contextField,
  epistemicCore,
  memoryRevision: 6,
  triage: cycle.triage,
  rejectedViewLedger: createRejectedViewLedger(now),
  plasticMemoryGraph: createPlasticMemoryGraph(now),
  outcome: {
    id: "outcome-atlas-1",
    viewId: selectedView,
    verdict: "partially_supported",
    expectedOutcome: "The previous context-loss mechanism fully explains the failure.",
    actualOutcome: "The invariant was relevant, but the transition path was the discriminating factor.",
    confidence: 0.88,
    independenceKey: "atlas-validation-1",
    contextFingerprint: "atlas-context-revision-1",
    discriminators: ["transition_path_missing", "initial_need_preserved"],
    revisitConditions: ["transition_path_restored"],
    capsuleIds: ["capsule-context-loss"],
    linkObservations: [
      {
        sourceId: "pattern-transition-loss",
        targetId: selectedView,
        relation: "enables_view",
        scope: { projectId: "project-atlas" },
        effect: "supports",
        weight: 0.82,
        independenceKey: "atlas-validation-1",
        contextIds: ["context-atlas-memory"],
        observedAt: "2026-07-30T18:10:00.000Z",
      },
    ],
    observedAt: "2026-07-30T18:10:00.000Z",
  },
});

console.log("Retroactive attention revision:", retroaction.attentionField.cycle);
console.log("Capsule refinement:", retroaction.capsuleRefinementPlans);
console.log("Plastic links:", retroaction.plasticity.graph.links);
